AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  chatbot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CrawlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: bot.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        Crawler:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /crawl
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CrawlerApi:
    Description: "API Gateway endpoint URL for Prod stage for CrawlerFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/crawl/"
  CrawlerFunction:
    Description: "CrawlerFunction ARN"
    Value: !GetAtt CrawlerFunction.Arn
  CrawlerFunctionIamRole:
    Description: "Implicit IAM Role created for CrawlerFunction"
    Value: !GetAtt CrawlerFunctionRole.Arn
