name: Pipeline

on:
  # workflow_dispatch:
  #   inputs:
  #     run_apply:
  #       type: boolean
  #       description: 'run terraform apply'
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - 'feature**'

env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'us-east-1'

jobs:
  terraform:
    if: github.event.pull_request.merged == true
    name: 'Run Terraform'
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.4.2
    
    steps:
      - name: Configure AWS Credentials Action For GitHub Actions Stage
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
      
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init
        working-directory: terraform_infrastructure

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform_infrastructure

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform_infrastructure

      # - name: Terraform Apply
      #   if: "${{ github.event.inputs.run_apply == 'true' }}"
      #   run: terraform apply -auto-approve
      #   working-directory: terraform_infrastructure

